version: '3.7'

services:
  node:
    network_mode: host
    build:
      context: .
      target: base
    env_file: ./.env
    user: "1000:1000"
    volumes:
      - ".:/node:rw"
    command: ["npm", "run", "start:server:dev"]
